add to-do items
Andromeda-Learning/vanilla-todo-app-EleneKikalishvili pull request #1
Opened 2020-03-03 21:46 UTC by EleneKikalishvili

you can add new items in the to-do list via clicking "enter" button or just press enter on the keyboard

2020-03-04 01:03 UTC, shavidzet requested changes

2020-03-04 01:03 UTC, shavidzet commented on index.html
> +    <input id="userinput" type="text" placeholder="enter items" />
Please read https://github.com/Andromeda-Learning/vanilla-todo-app-DakoMumladze/pull/1#discussion_r387117259

2020-03-04 09:36 UTC, DakoMumladze requested changes
როცა ინფუთში არაფერს ვწერ მაინც ამატებს ლისტში, შეგიძლია შეამოწმო input.value და თუ ცარიელი არ იქნება მხოლოდ მაშინ დაემატოს .

2020-03-07 15:04 UTC, DakoMumladze submitted a review, later dismissed

2020-03-07 15:18 UTC, Anzormumladze submitted a review, later dismissed

2020-03-07 20:12 UTC, salolipartia approved these changes

2020-03-07 20:13 UTC, salolipartia submitted a review, later dismissed

2020-03-08 13:28 UTC, DakoMumladze submitted a review, later dismissed

2020-03-08 13:36 UTC, shavidzet requested changes
`<form>` უნდა გეწეროს jsში

2020-03-08 14:11 UTC, DakoMumladze submitted a review, later dismissed

2020-03-08 14:30 UTC, Anzormumladze submitted a review, later dismissed

2020-03-08 14:45 UTC, shavidzet requested changes

2020-03-08 14:45 UTC, shavidzet commented on script.js
> +let ul = document.querySelector("ul");
please use `const` instead of `let`

2020-03-08 16:43 UTC, DakoMumladze submitted a review, later dismissed

2020-03-09 11:19 UTC, Anzormumladze submitted a review, later dismissed

2020-03-11 06:27 UTC, salolipartia submitted a review, later dismissed

2020-03-12 18:02 UTC, shavidzet approved these changes

2020-03-12 18:02 UTC, shavidzet commented on script.js
> +  if (input.value.length > 0 && input.value.replace(/\s/g, ""))
Please use .trim function

2020-03-12 18:02 UTC, shavidzet commented on script.js
> +  e.preventDefault();
ეს ფუნქციის პირველ ხაზზე უნდა ეწერროს, მე15ეზე

2020-03-13 07:40 UTC, DakoMumladze approved these changes

2020-03-13 07:40 UTC, merged