Delete Button
Andromeda-Learning/vanilla-todo-app-EleneKikalishvili pull request #3
Opened 2020-03-04 11:15 UTC by EleneKikalishvili

on click, user can delete to-do list item

2020-03-07 15:14 UTC, DakoMumladze submitted a review, later dismissed

2020-03-11 05:08 UTC, salolipartia submitted a review, later dismissed

2020-03-13 13:17 UTC, DakoMumladze requested changes
Please change renBtn and delBtn variables to const, because their values don't change

2020-03-13 13:25 UTC, DakoMumladze approved these changes

2020-03-13 13:27 UTC, Anzormumladze approved these changes

2020-03-13 13:29 UTC, merged